name: CI - Spotless & Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Check Formatting and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use OpenJDK from Eclipse Temurin
          java-version: '17'       # Match your project's Java version

      - name: Build with Gradle
        run: ./gradlew quarkusBuild -i

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck

      - name: Run Tests
        run: ./gradlew test -i
